# index:
#    path: /
#    controller: App\Controller\SecurityController::login

homepage:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
    defaults:
        route: app_login
        # make a permanent redirection...
        permanent: true

backend:
    path: /admin
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
    defaults:
        route: backend_dashboard
        # make a permanent redirection...
        permanent: true



# authentication_token:
#     path: /authentication_token
#     controller: authentication_token
#     methods: ['POST']

api_login_check:
   path: /api/login
   methods: [POST]